// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ReghRA9fxc9u8SGRQ1Mt__y4JsaBkbw',
    appId: '1:1048390334337:android:897dd7ed0da077f9289a80',
    messagingSenderId: '1048390334337',
    projectId: 'safar-6b838',
    databaseURL: 'https://safar-6b838-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safar-6b838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvxAiNLCCuiNvUhKPsx2CHk5jXng2Vduc',
    appId: '1:1048390334337:ios:95276f8ff6894e00289a80',
    messagingSenderId: '1048390334337',
    projectId: 'safar-6b838',
    databaseURL: 'https://safar-6b838-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safar-6b838.appspot.com',
    iosBundleId: 'com.example.safar',
  );

}